[project]
name = "workbench"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.7"
dependencies = ["loguru~= 0.7.3"]

[dependency-groups]
dev = ["pytest~=8.3.4"]
lint = ["ruff~=0.8.4"]
